name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  program-pi:
      runs-on: ubuntu-latest
      container:
        image: z88dk/z88dk
      steps:
      - uses: actions/checkout@v3
      - name: Compile program
        run: cd pi && make
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: pi.bin
          path: pi/pi.bin